# Generated by Django 6.1 on 2026-08-29 11:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('customers', '0001_initial'),
        ('products', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('invoice_number', models.CharField(max_length=30, unique=True, verbose_name='شماره فاکتور')),
                ('customer_name', models.CharField(blank=True, max_length=200, verbose_name='نام مشتری')),
                ('customer_phone', models.CharField(blank=True, max_length=15, verbose_name='تلفن مشتری')),
                ('customer_address', models.TextField(blank=True, verbose_name='آدرس مشتری')),
                ('seller_name', models.CharField(blank=True, max_length=200, verbose_name='نام فروشنده')),
                ('seller_business', models.CharField(blank=True, max_length=200, verbose_name='نام کسب\u200cوکار')),
                ('seller_address', models.TextField(blank=True, verbose_name='آدرس فروشنده')),
                ('seller_phone', models.CharField(blank=True, max_length=15, verbose_name='تلفن فروشنده')),
                ('invoice_date', models.DateField(verbose_name='تاریخ فاکتور')),
                ('due_date', models.DateField(blank=True, null=True, verbose_name='تاریخ سررسید')),
                ('subtotal', models.DecimalField(decimal_places=0, default=0, max_digits=15, verbose_name='جمع')),
                ('item_taxes_total', models.DecimalField(decimal_places=0, default=0, max_digits=15, verbose_name='جمع مالیات اقلام')),
                ('invoice_tax_rate', models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='نرخ مالیات فاکتور')),
                ('invoice_tax_amount', models.DecimalField(decimal_places=0, default=0, max_digits=15, verbose_name='مالیات فاکتور')),
                ('discount_type', models.CharField(blank=True, choices=[('percent', 'درصد'), ('amount', 'مبلغ')], max_length=10, verbose_name='نوع تخفیف')),
                ('discount_value', models.DecimalField(decimal_places=0, default=0, max_digits=15, verbose_name='مقدار تخفیف')),
                ('discount_amount', models.DecimalField(decimal_places=0, default=0, max_digits=15, verbose_name='مبلغ تخفیف')),
                ('final_amount', models.DecimalField(decimal_places=0, default=0, max_digits=15, verbose_name='مبلغ نهایی')),
                ('bank_name', models.CharField(blank=True, max_length=100, verbose_name='نام بانک')),
                ('card_number', models.CharField(blank=True, max_length=20, verbose_name='شماره کارت')),
                ('iban', models.CharField(blank=True, max_length=30, verbose_name='شماره شبا')),
                ('account_holder', models.CharField(blank=True, max_length=200, verbose_name='صاحب حساب')),
                ('notes', models.TextField(blank=True, verbose_name='توضیحات')),
                ('seller_signature', models.ImageField(blank=True, null=True, upload_to='signatures/', verbose_name='امضای فروشنده')),
                ('customer_signature', models.ImageField(blank=True, null=True, upload_to='signatures/', verbose_name='امضای مشتری')),
                ('is_paid', models.BooleanField(default=False, verbose_name='پرداخت شده')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('customer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='invoices', to='customers.customer', verbose_name='مشتری')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invoices', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'فاکتور',
                'verbose_name_plural': 'فاکتورها',
                'ordering': ['-invoice_date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='InvoiceItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=200, verbose_name='نام کالا')),
                ('quantity', models.DecimalField(decimal_places=2, default=1, max_digits=10, verbose_name='تعداد')),
                ('unit_price', models.DecimalField(decimal_places=0, max_digits=15, verbose_name='قیمت واحد')),
                ('tax_rate', models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='نرخ مالیات')),
                ('total_price', models.DecimalField(decimal_places=0, default=0, max_digits=15, verbose_name='مبلغ کل')),
                ('tax_amount', models.DecimalField(decimal_places=0, default=0, max_digits=15, verbose_name='مالیات')),
                ('unit', models.CharField(blank=True, default='عدد', max_length=20, verbose_name='واحد')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='ردیف')),
                ('invoice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='invoices.invoice')),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='invoice_items', to='products.product')),
            ],
            options={
                'verbose_name': 'قلم فاکتور',
                'verbose_name_plural': 'اقلام فاکتور',
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='InvoiceNumberSequence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField()),
                ('last_number', models.IntegerField(default=0)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'year')},
            },
        ),
    ]
