# Generated by Django 6.1 on 2026-08-29 16:09

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='invoice_number',
            field=models.CharField(max_length=30, verbose_name='شماره فاکتور'),
        ),
        migrations.AlterUniqueTogether(
            name='invoice',
            unique_together={('user', 'invoice_number')},
        ),
    ]
