# Generated by Django 6.1 on 2026-09-01 06:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0002_alter_invoice_invoice_number_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoiceitem',
            name='frequency',
            field=models.CharField(blank=True, default='', max_length=10, verbose_name='دوره تکرار'),
        ),
    ]
