# Generated by Django 6.1 on 2026-09-02 18:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0003_add_item_frequency'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='idempotency_key',
            field=models.CharField(blank=True, db_index=True, max_length=64, verbose_name='کلید عدم تکرار'),
        ),
        migrations.AddField(
            model_name='invoice',
            name='version',
            field=models.IntegerField(default=0, verbose_name='نسخه'),
        ),
    ]
