# Generated by Django 6.1 on 2026-08-29 11:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Bank',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='نام بانک')),
                ('code', models.CharField(blank=True, max_length=10, verbose_name='کد بانک')),
                ('logo', models.ImageField(blank=True, null=True, upload_to='bank_logos/')),
            ],
            options={
                'verbose_name': 'بانک',
                'verbose_name_plural': 'بانک\u200cها',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='BankAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('card_number', models.CharField(max_length=16, verbose_name='شماره کارت')),
                ('iban', models.CharField(max_length=30, verbose_name='شماره شبا')),
                ('account_holder', models.CharField(max_length=200, verbose_name='صاحب حساب')),
                ('account_number', models.CharField(blank=True, max_length=20, verbose_name='شماره حساب')),
                ('is_default', models.BooleanField(default=False, verbose_name='پیش\u200cفرض')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('bank', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='accounts', to='banks.bank', verbose_name='بانک')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bank_accounts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'حساب بانکی',
                'verbose_name_plural': 'حساب\u200cهای بانکی',
                'ordering': ['-is_default', '-created_at'],
            },
        ),
    ]
