# Generated by Django 6.1 on 2026-09-02 21:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_add_custom_units'),
    ]

    operations = [
        migrations.CreateModel(
            name='OTPCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code_hash', models.CharField(max_length=64, verbose_name='هش کد')),
                ('purpose', models.CharField(choices=[('login', 'ورود'), ('password_change', 'تغییر رمز'), ('email_verify', 'تأیید ایمیل')], max_length=20, verbose_name='منظور')),
                ('attempts', models.IntegerField(default=0, verbose_name='تعداد تلاش')),
                ('is_used', models.BooleanField(default=False, verbose_name='استفاده شده')),
                ('expires_at', models.DateTimeField(verbose_name='انقضا')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='otp_codes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'کد یکبارمصرف',
                'verbose_name_plural': 'کدهای یکبارمصرف',
                'ordering': ['-created_at'],
            },
        ),
    ]
