# Generated by Django 6.1 on 2026-08-29 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='frequency',
            field=models.CharField(blank=True, choices=[('', ''), ('hourly', 'ساعتی'), ('daily', 'روزانه'), ('weekly', 'هفتگی'), ('monthly', 'ماهانه'), ('yearly', 'سالانه')], default='', max_length=10, verbose_name='دوره تکرار'),
        ),
    ]
